// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Delete Category
    #
    # + categoryPublicId - The unique ID of the Category
    # + return - returns can be any of following types 
    # http:NoContent (No Content)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function delete categories/[int categoryPublicId]() returns http:NoContent|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return http:NO_CONTENT;
    }

    # Delete Epic
    #
    # + epicPublicId - The unique ID of the Epic
    # + return - returns can be any of following types 
    # http:NoContent (No Content)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function delete epics/[int epicPublicId]() returns http:NoContent|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return http:NO_CONTENT;
    }

    # Delete Story
    #
    # + storyPublicId - The ID of the Story
    # + return - returns can be any of following types 
    # http:NoContent (No Content)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function delete stories/[int storyPublicId]() returns http:NoContent|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return http:NO_CONTENT;
    }

    # List Categories
    #
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get categories() returns Category[]|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return [mockCategory(1, "Engineering"), mockCategory(2, "Marketing")];
    }

    # Get Category
    #
    # + categoryPublicId - The unique ID of the Category
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get categories/[int categoryPublicId]() returns Category|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockCategory(categoryPublicId, "Engineering");
    }

    # List Epics
    #
    # + includesDescription - A true/false boolean indicating whether to return Epics with their descriptions
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get epics(@http:Query {name: "includes_description"} boolean? includesDescription) returns EpicSlim[]|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return [mockEpicSlim(101, "Q3 Platform Launch"), mockEpicSlim(102, "Mobile Onboarding Revamp")];
    }

    # Get Epic
    #
    # + epicPublicId - The unique ID of the Epic
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get epics/[int epicPublicId]() returns Epic|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockEpic(epicPublicId, "Q3 Platform Launch");
    }

    # List Iterations
    #
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get iterations() returns IterationSlim[]|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return [mockIterationSlim(201, "Sprint 42"), mockIterationSlim(202, "Sprint 43")];
    }

    # Get Iteration
    #
    # + iterationPublicId - The unique ID of the Iteration
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get iterations/[int iterationPublicId]() returns Iteration|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockIteration(iterationPublicId, "Sprint 42");
    }

    # List Labels
    #
    # + slim - A true/false boolean indicating if the slim versions of the Label should be returned
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get labels(boolean? slim) returns Label[]|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return [mockLabel(301, "backend"), mockLabel(302, "customer-feedback")];
    }

    # Get Label
    #
    # + labelPublicId - The unique ID of the Label
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get labels/[int labelPublicId]() returns Label|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockLabel(labelPublicId, "backend");
    }

    # List Members
    #
    # + orgPublicId - The unique ID of the Organization to limit the list to
    # + disabled - Filter members by their disabled state. If true, return only disabled members. If false, return only enabled members
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get members(@http:Query {name: "org-public-id"} string? orgPublicId, boolean? disabled) returns Member[]|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return [mockMember("5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f", "Jane Doe"), mockMember("6a0c4d2f-8b3e-4d2c-8f72-1b2c3d4e5f60", "John Smith")];
    }

    # Get Member
    #
    # + memberPublicId - The Member's unique ID
    # + orgPublicId - The unique ID of the Organization to limit the lookup to
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get members/[string memberPublicId](@http:Query {name: "org-public-id"} string? orgPublicId) returns Member|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockMember(memberPublicId, "Jane Doe");
    }

    # Search Stories
    #
    # + query - See our help center article on [search operators](https://help.shortcut.com/hc/en-us/articles/360000046646-Search-Operators)
    # + pageSize - The number of search results to include in a page. Minimum of 1 and maximum of 250
    # + detail - The amount of detail included in each result item.
    # "full" will include all descriptions and comments and more fields on
    # related items such as pull requests, branches and tasks.
    # "slim" omits larger fulltext fields such as descriptions and comments
    # and only references related items by id.
    # The default is "full"
    # + next - The next page token
    # + entityTypes - A collection of entity_types to search. Defaults to story and epic. Supports: epic, iteration, objective, story
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (**Either:** (1) Schema mismatch **or** (2) Maximum of 1000 search results exceeded )
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get search/stories(string query, @http:Query {name: "page_size"} int? pageSize, string? detail, string? next, @http:Query {name: "entity_types"} string[]? entityTypes) returns StorySearchResults|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return {total: 1, next: (), data: [mockStorySearchResult(401, "Fix login redirect loop")]};
    }

    # Get Story
    #
    # + storyPublicId - The ID of the Story
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get stories/[int storyPublicId]() returns Story|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockStory(storyPublicId, "Fix login redirect loop");
    }

    # List Workflows
    #
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get workflows() returns Workflow[]|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return [mockWorkflow(501, "Engineering Workflow")];
    }

    # Get Workflow
    #
    # + workflowPublicId - The ID of the Workflow
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function get workflows/[int workflowPublicId]() returns Workflow|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockWorkflow(workflowPublicId, "Engineering Workflow");
    }

    # Create Category
    #
    # + payload - Payload for the Create Category operation 
    # + return - returns can be any of following types 
    # http:Created (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function post categories(@http:Payload CreateCategory payload) returns Category|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockCategory(3, payload.name);
    }

    # Create Epic
    #
    # + payload - Payload for the Create Epic operation 
    # + return - returns can be any of following types 
    # http:Created (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function post epics(@http:Payload CreateEpic payload) returns Epic|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockEpic(103, payload.name);
    }

    # Create Iteration
    #
    # + payload - Payload for the Create Iteration operation 
    # + return - returns can be any of following types 
    # http:Created (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function post iterations(@http:Payload CreateIteration payload) returns Iteration|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockIteration(203, payload.name);
    }

    # Create Label
    #
    # + payload - Request parameters for creating a Label on a Shortcut Story 
    # + return - returns can be any of following types 
    # http:Created (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function post labels(@http:Payload CreateLabelParams payload) returns Label|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockLabel(303, payload.name);
    }

    # Create Story
    #
    # + payload - Request parameters for creating a story 
    # + return - returns can be any of following types 
    # http:Created (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function post stories(@http:Payload CreateStoryParams payload) returns Story|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockStory(402, payload.name);
    }

    # Update Category
    #
    # + categoryPublicId - The unique ID of the Category you wish to update
    # + payload - Payload for the Update Category operation 
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function put categories/[int categoryPublicId](@http:Payload UpdateCategory payload) returns Category|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockCategory(categoryPublicId, payload.name ?: "Engineering");
    }

    # Update Epic
    #
    # + epicPublicId - The unique ID of the Epic
    # + payload - Payload for the Update Epic operation 
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function put epics/[int epicPublicId](@http:Payload UpdateEpic payload) returns Epic|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockEpic(epicPublicId, payload.name ?: "Q3 Platform Launch");
    }

    # Update Story
    #
    # + storyPublicId - The unique identifier of this story
    # + payload - Payload for the Update Story operation 
    # + return - returns can be any of following types 
    # http:Ok (Resource)
    # http:BadRequest (Schema mismatch)
    # http:NotFound (Resource does not exist)
    # http:UnprocessableEntity (Unprocessable)
    resource function put stories/[int storyPublicId](@http:Payload UpdateStory payload) returns Story|http:BadRequest|http:NotFound|http:UnprocessableEntity {
        return mockStory(storyPublicId, payload.name ?: "Fix login redirect loop");
    }
}

function mockStats() returns IterationStats => {
    numPointsDone: 20, numPointsBacklog: 5, numPointsStarted: 8, numStoriesBacklog: 2, numPoints: 33,
    numStoriesStarted: 3, numStoriesUnstarted: 2, numPointsUnstarted: 5, numStoriesUnestimated: 1,
    numRelatedDocuments: 0, numStoriesDone: 7
};

function mockCategory(int id, string name) returns Category => {
    archived: false, entityType: "category", color: "#6515dd", updatedAt: "2024-05-01T10:15:30Z", name,
    globalId: "v2:category:" + id.toString(), createdAt: "2024-01-10T08:00:00Z", externalId: (), id, 'type: "milestone"
};

function mockEpicStats() returns EpicStats => {
    lastStoryUpdate: "2024-05-01T10:15:30Z", numPointsDone: 20, numPointsBacklog: 5, numPointsStarted: 8,
    numStoriesBacklog: 2, numPoints: 33, numStoriesStarted: 3, numStoriesUnstarted: 2, numPointsUnstarted: 5,
    numStoriesUnestimated: 1, numRelatedDocuments: 0, numStoriesTotal: 12, numStoriesDone: 7
};

function mockEpicSlim(int id, string name) returns EpicSlim => {
    requestedById: "5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f", productboardName: (), milestoneId: (),
    productboardPluginId: (), createdAt: "2024-01-10T08:00:00Z", groupMentionIds: [], externalId: (),
    archived: false, associatedGroups: [], storiesWithoutProjects: 0, updatedAt: "2024-05-01T10:15:30Z",
    stats: mockEpicStats(), epicStateId: 500000010, productboardUrl: (), followerIds: [], groupIds: [],
    state: "in progress", id, deadline: "2024-09-30T00:00:00Z", memberMentionIds: [],
    appUrl: "https://app.shortcut.com/acme/epic/" + id.toString(), productboardId: (), labelIds: [],
    globalId: "v2:epic:" + id.toString(), started: true, completed: false, projectIds: [], labels: [],
    objectiveIds: [], completedAt: (), entityType: "epic", startedAtOverride: (), groupId: (), name,
    plannedStartDate: "2024-07-01T00:00:00Z", startedAt: "2024-07-02T09:00:00Z", position: 1,
    completedAtOverride: (), ownerIds: ["5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f"], mentionIds: []
};

function mockEpic(int id, string name) returns Epic => {
    requestedById: "5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f", productboardName: (), milestoneId: (),
    description: "Deliver the platform capabilities planned for the third quarter.",
    productboardPluginId: (), createdAt: "2024-01-10T08:00:00Z", groupMentionIds: [], externalId: (),
    archived: false, associatedGroups: [], storiesWithoutProjects: 0, updatedAt: "2024-05-01T10:15:30Z",
    stats: mockEpicStats(), epicStateId: 500000010, productboardUrl: (), followerIds: [], groupIds: [],
    state: "in progress", id, deadline: "2024-09-30T00:00:00Z", memberMentionIds: [],
    appUrl: "https://app.shortcut.com/acme/epic/" + id.toString(), comments: [], productboardId: (),
    labelIds: [], globalId: "v2:epic:" + id.toString(), started: true, completed: false, projectIds: [],
    labels: [], objectiveIds: [], completedAt: (), entityType: "epic", startedAtOverride: (), groupId: (), name,
    plannedStartDate: "2024-07-01T00:00:00Z", startedAt: "2024-07-02T09:00:00Z", position: 1,
    completedAtOverride: (), ownerIds: ["5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f"], mentionIds: []
};

function mockIterationSlim(int id, string name) returns IterationSlim => {
    memberMentionIds: [], endDate: "2024-06-14T00:00:00Z", appUrl: "https://app.shortcut.com/acme/iteration/" + id.toString(),
    labelIds: [], globalId: "v2:iteration:" + id.toString(), createdAt: "2024-05-27T08:00:00Z", groupMentionIds: [],
    labels: [], entityType: "iteration", associatedGroups: [], updatedAt: "2024-06-01T10:00:00Z", stats: mockStats(),
    followerIds: [], name, groupIds: [], id, mentionIds: [], startDate: "2024-06-01T00:00:00Z", status: "started"
};

function mockIteration(int id, string name) returns Iteration => {
    memberMentionIds: [], endDate: "2024-06-14T00:00:00Z", appUrl: "https://app.shortcut.com/acme/iteration/" + id.toString(),
    labelIds: [], globalId: "v2:iteration:" + id.toString(), description: "Two week delivery cycle for the platform team.",
    createdAt: "2024-05-27T08:00:00Z", groupMentionIds: [], labels: [], entityType: "iteration", associatedGroups: [],
    updatedAt: "2024-06-01T10:00:00Z", stats: mockStats(), followerIds: [], name, groupIds: [], id, mentionIds: [],
    startDate: "2024-06-01T00:00:00Z", status: "started"
};

function mockLabel(int id, string name) returns Label => {
    archived: false, appUrl: "https://app.shortcut.com/acme/label/" + id.toString(), entityType: "label",
    color: "#ff0000", updatedAt: "2024-05-01T10:15:30Z", name, globalId: "v2:label:" + id.toString(),
    description: "Work related to " + name, createdAt: "2024-01-10T08:00:00Z", externalId: (), id
};

function mockMember(string id, string name) returns Member => {
    role: "member", profile: {
        mentionName: "jdoe", isOwner: false, deactivated: false, gravatarHash: (), entityType: "profile",
        emailAddress: "jane.doe@example.com", displayIcon: {entityType: "icon", updatedAt: "2024-04-12T14:00:00Z", createdAt: "2023-11-02T09:30:00Z", id: "8c2e6f4b-ad5a-4f4e-b194-3d4e5f607182", url: "https://example.com/avatar.png"}, name, id: "7b1d5e3a-9c4f-4e3d-a083-2c3d4e5f6071"
    },
    globalId: "v2:member:" + id, createdAt: "2023-11-02T09:30:00Z", entityType: "member", updatedAt: "2024-04-12T14:00:00Z",
    groupIds: [], disabled: false, state: "full", id, createdWithoutInvite: false
};

function mockWorkflowState(int id, string name, string 'type) returns WorkflowState => {
    numStories: 4, verb: (), globalId: "v2:workflow-state:" + id.toString(), description: "", createdAt: "2023-11-02T09:30:00Z",
    'type, entityType: "workflow-state", updatedAt: "2024-04-12T14:00:00Z", name, id, position: id, numStoryTemplates: 0
};

function mockWorkflow(int id, string name) returns Workflow => {
    entityType: "workflow", updatedAt: "2024-04-12T14:00:00Z", name, description: "Default workflow for engineering stories",
    createdAt: "2023-11-02T09:30:00Z", id, teamId: 10, autoAssignOwner: false, projectIds: [],
    defaultStateId: 500000001,
    states: [mockWorkflowState(500000001, "Unscheduled", "unstarted"), mockWorkflowState(500000002, "In Development", "started"), mockWorkflowState(500000003, "Completed", "done")]
};

function mockStory(int id, string name) returns Story => {
    workflowStateId: 500000002, workflowId: 500000000, requestedById: "5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f",
    pullRequests: [], storyTemplateId: (), projectId: (), stats: {numRelatedDocuments: 0}, estimate: 3, id, tasks: [],
    labelIds: [], globalId: "v2:story:" + id.toString(), completed: false, branches: [], labels: [], iterationId: (),
    completedAt: (), previousIterationIds: [], externalLinks: [], name, startedAt: "2024-06-03T09:00:00Z", commits: [],
    files: [], position: 1, completedAtOverride: (), ownerIds: ["5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f"], mentionIds: [],
    blocker: false, linkedFiles: [], description: "Users are redirected back to the login page after authenticating.",
    createdAt: "2024-06-01T08:00:00Z", groupMentionIds: [], externalId: (), storyType: "bug", archived: false,
    updatedAt: "2024-06-03T09:00:00Z", blocked: false, followerIds: [], deadline: (), memberMentionIds: [],
    appUrl: "https://app.shortcut.com/acme/story/" + id.toString(), comments: [], storyLinks: [], started: true,
    movedAt: (), entityType: "story", startedAtOverride: (), groupId: (), epicId: ()
};

function mockStorySearchResult(int id, string name) returns StorySearchResult => {
    workflowStateId: 500000002, workflowId: 500000000, requestedById: "5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f",
    storyTemplateId: (), projectId: (), stats: {numRelatedDocuments: 0}, estimate: 3, id, labelIds: [],
    globalId: "v2:story:" + id.toString(), completed: false, labels: [], iterationId: (), completedAt: (),
    previousIterationIds: [], externalLinks: [], name, startedAt: "2024-06-03T09:00:00Z", position: 1,
    completedAtOverride: (), ownerIds: [], mentionIds: [], blocker: false, createdAt: "2024-06-01T08:00:00Z",
    groupMentionIds: [], externalId: (), storyType: "bug", archived: false, updatedAt: "2024-06-03T09:00:00Z",
    blocked: false, followerIds: [], deadline: (), memberMentionIds: [],
    appUrl: "https://app.shortcut.com/acme/story/" + id.toString(), storyLinks: [], started: true, movedAt: (),
    entityType: "story", startedAtOverride: (), groupId: (), epicId: ()
};
