// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations

import ballerina/http;
import ballerina/os;
import ballerina/test;

final boolean isLiveServer = os:getEnv("IS_LIVE_SERVER") == "true";
final string serviceUrl = isLiveServer ? "https://api.app.shortcut.com/api/v3" : "http://localhost:9090";
final string token = isLiveServer ? os:getEnv("SHORTCUT_API_TOKEN") : "test_token";

final Client shortcut = check new ({shortcutToken: token}, {httpVersion: http:HTTP_1_1}, serviceUrl);

// IDs of the resources created by the create tests. The get, update and list tests use them,
// and `cleanUp` deletes them after a live run.
int categoryId = 0;
int epicId = 0;
int storyId = 0;
int labelId = 0;
int iterationId = 0;

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateCategory() returns error? {
    Category response = check shortcut->createCategory({name: "Platform"});
    test:assertEquals(response.name, "Platform");
    categoryId = response.id;
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateCategory]}
function testListCategories() returns error? {
    Category[] response = check shortcut->listCategories();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateCategory]}
function testGetCategory() returns error? {
    Category response = check shortcut->getCategory(categoryId);
    test:assertEquals(response.id, categoryId);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testGetCategory]}
function testUpdateCategory() returns error? {
    Category response = check shortcut->updateCategory(categoryId, {name: "Platform Engineering"});
    test:assertEquals(response.name, "Platform Engineering");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteCategory() returns error? {
    Category created = check shortcut->createCategory({name: "Temporary"});
    check shortcut->deleteCategory(created.id);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateEpic() returns error? {
    Epic response = check shortcut->createEpic({name: "Q4 Roadmap"});
    test:assertEquals(response.name, "Q4 Roadmap");
    epicId = response.id;
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateEpic]}
function testListEpics() returns error? {
    EpicSlim[] response = check shortcut->listEpics();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateEpic]}
function testGetEpic() returns error? {
    Epic response = check shortcut->getEpic(epicId);
    test:assertEquals(response.id, epicId);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testGetEpic]}
function testUpdateEpic() returns error? {
    Epic response = check shortcut->updateEpic(epicId, {name: "Q4 Roadmap Updated"});
    test:assertEquals(response.name, "Q4 Roadmap Updated");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteEpic() returns error? {
    Epic created = check shortcut->createEpic({name: "Temporary epic"});
    check shortcut->deleteEpic(created.id);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateStory() returns error? {
    Story response = check shortcut->createStory({name: "Add SSO support"});
    test:assertEquals(response.name, "Add SSO support");
    storyId = response.id;
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateStory]}
function testGetStory() returns error? {
    Story response = check shortcut->getStory(storyId);
    test:assertEquals(response.id, storyId);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testGetStory]}
function testUpdateStory() returns error? {
    Story response = check shortcut->updateStory(storyId, {name: "Add SSO support v2"});
    test:assertEquals(response.name, "Add SSO support v2");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteStory() returns error? {
    Story created = check shortcut->createStory({name: "Temporary story"});
    check shortcut->deleteStory(created.id);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateLabel() returns error? {
    Label response = check shortcut->createLabel({name: "tech-debt"});
    test:assertEquals(response.name, "tech-debt");
    labelId = response.id;
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateLabel]}
function testListLabels() returns error? {
    Label[] response = check shortcut->listLabels();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateLabel]}
function testGetLabel() returns error? {
    Label response = check shortcut->getLabel(labelId);
    test:assertEquals(response.id, labelId);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListMembers() returns error? {
    Member[] response = check shortcut->listMembers();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testListMembers]}
function testGetMember() returns error? {
    Member[] members = check shortcut->listMembers();
    Member response = check shortcut->getMember(members[0].id);
    test:assertEquals(response.id, members[0].id);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListWorkflows() returns error? {
    Workflow[] response = check shortcut->listWorkflows();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testListWorkflows]}
function testGetWorkflow() returns error? {
    Workflow[] workflows = check shortcut->listWorkflows();
    Workflow response = check shortcut->getWorkflow(workflows[0].id);
    test:assertEquals(response.id, workflows[0].id);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateIteration() returns error? {
    Iteration response = check shortcut->createIteration({name: "Sprint 44", startDate: "2024-07-01", endDate: "2024-07-14"});
    test:assertEquals(response.name, "Sprint 44");
    iterationId = response.id;
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateIteration]}
function testListIterations() returns error? {
    IterationSlim[] response = check shortcut->listIterations();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"], dependsOn: [testCreateIteration]}
function testGetIteration() returns error? {
    Iteration response = check shortcut->getIteration(iterationId);
    test:assertEquals(response.id, iterationId);
}

// Search results depend on the workspace's existing stories and on asynchronous indexing,
// so this runs against the mock only.
@test:Config {groups: ["mock_tests"]}
function testSearchStories() returns error? {
    StorySearchResults response = check shortcut->searchStories(query = "login");
    test:assertTrue(response.data.length() > 0);
}

@test:AfterSuite {alwaysRun: true}
function cleanUp() returns error? {
    if !isLiveServer {
        return;
    }
    if storyId != 0 {
        check shortcut->deleteStory(storyId);
    }
    if epicId != 0 {
        check shortcut->deleteEpic(epicId);
    }
    if categoryId != 0 {
        check shortcut->deleteCategory(categoryId);
    }
    if labelId != 0 {
        check shortcut->deleteLabel(labelId);
    }
    if iterationId != 0 {
        check shortcut->deleteIteration(iterationId);
    }
}
